apiVersion: v1
kind: Service
metadata:
  name: cuda-networks-docs-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30008
  selector:
    app: cuda-networks-docs
